apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-04-18T12:00:00Z"
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2024-04-18T12:00:00Z"
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: 
status: {}
