apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-pod
  name: sample-pod
spec:
  containers:
  - image: nginx
    name: sample-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
