apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sample-pod
  name: sample-pod
spec:
  containers:
    - image: nginx
      name: sample-pod


##  kubectl run sample-pod --image=nginx --dry-run=client -o yaml > sample-pod.yaml