apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-10T00:00:00Z"
  labels:
    run: first-pod
  name: first-pod
spec:
  containers:
  - image: nginx
    name: first-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# kubectl run first-pod --image=nginx --dry-run=client -o yaml > sample-pod.yaml