apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sample-pod
  name: sample-pod
spec:
  containers:
  - image: nginx
    name: sample-pod
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
