apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: first-pod
  name: first-pod
spec:
  containers:
  - image: nginx
    name: first-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
